import { Table, Badge, Dropdown } from 'antd';
import { SettingFilled, UserOutlined } from '@ant-design/icons';
const handleButtonClick = e => {
    message.info('Click on left button.');
    console.log('click left button', e);
};
const handleMenuClick = e => {
    message.info('Click on menu item.');
    console.log('click', e);
};
const items = [
    {
        label: '1st menu item',
        key: '1',
        icon: <UserOutlined />,
    },
    {
        label: '2nd menu item',
        key: '2',
        icon: <UserOutlined />,
    },
    {
        label: '3rd menu item',
        key: '3',
        icon: <UserOutlined />,
        danger: true,
    },
    {
        label: '4rd menu item',
        key: '4',
        icon: <UserOutlined />,
        danger: true,
        disabled: true,
    },
];
const menuProps = {
    items,
    onClick: handleMenuClick,
};
const columns = [
    {
        title: 'ID Solicitud',
        dataIndex: 'requestID',
        width: 100,
        render: (_, record) => {
            return record.requestID.toString().substring(1, 8);
        },
    },
    {
        title: 'Fecha Apertura',
        dataIndex: 'startDateVancancy',
        defaultSortOrder: 'descend',
        sorter: (a, b) => a.startDate - b.startDate,
    },
    {
        title: 'Fecha Ingreso',
        dataIndex: 'entryDateEmployee',
        defaultSortOrder: 'descend',
        sorter: (a, b) => a.entryDateEmployee - b.entryDateEmployee,
    },
    {
        title: 'Worker Type',
        dataIndex: 'workerType',
        defaultSortOrder: 'descend',
        width: 100,
        sorter: (a, b) => a.workerType - b.workerType,
    },
    {
        title: 'Job Title',
        dataIndex: 'jobTitle',
        defaultSortOrder: 'descend',
        sorter: (a, b) => a.jobTitle - b.jobTitle,
    },
    {
        title: 'Office',
        dataIndex: 'office',
        defaultSortOrder: 'descend',
        sorter: (a, b) => a.office - b.office,
    },
    {
        title: 'Solicitante',
        dataIndex: 'requestedBy',
        defaultSortOrder: 'descend',
        ellipsis: true,
        sorter: (a, b) => a.requestedBy - b.requestedBy,
    },
    {
        title: 'LoS',
        dataIndex: 'los',
        defaultSortOrder: 'descend',
        sorter: (a, b) => a.los - b.los,
        width: 90,
    },
    {
        title: 'Estado Solicitud',
        dataIndex: 'requestStatus',
        width: '80px',
        render: (_, record) => {
            const value = record.requestStatus;

            if (value === 'Aprobado') {
                return <Badge key={record.requestID} color="green" className="flex justify-center w-full" />;
            } else if (value === 'Rechazado') {
                return <Badge key={record.requestID} color="red" className="flex justify-center w-full" />;
            } else {
                return <Badge key={record.requestID} color="yellow" className="flex justify-center w-full" />;
            }
        },
    },
    {
        title: 'Vacante Creada',
        dataIndex: 'vacancyIsCreated',
        defaultSortOrder: 'descend',
        sorter: (a, b) => a.vacancyIsCreated - b.vacancyIsCreated,
        render: (_, record) => {
            const value = record.vacancyIsCreated;

            if (value === 'Creada') {
                return <Badge key={record.requestID} color="green" className="flex justify-center w-full" />;
            } else {
                return <Badge key={record.requestID} color="yellow" className="flex justify-center w-full" />;
            }
        },
    },
    {
        title: 'Total Cupos Disponibles',
        dataIndex: 'totalVacancies',
        defaultSortOrder: 'descend',
        sorter: (a, b) => a.totalVacancies - b.totalVacancies,
    },
    {
        title: 'Acción',
        dataIndex: 'action',
        width: 80,
        render: (_, record) => {
            return (
                <Dropdown menu={menuProps} trigger={['click']}>
                    <div className="bg-[#FFB600] text-black text-center pb-1 cursor-pointer">
                        <SettingFilled className="text-sm self-center" />
                    </div>
                </Dropdown>
            );
        },
    },
];
const data = [
    {
        requestID: 'b62995e4-a3ff-4db1-8232-584c19256cf9',
        startDateVancancy: '8/8/2022',
        entryDateEmployee: '10/27/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Senior Associate 2',
        office: 'Santiago',
        requestedBy: 'medgeon0@comcast.net',
        los: 'Tax',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 6,
        action: 'eget',
    },
    {
        requestID: 'bf25f9c0-47a6-4372-962b-14b8bf88c10f',
        startDateVancancy: '10/16/2022',
        entryDateEmployee: '4/26/2022',
        workerType: 'Socio',
        jobTitle: 'Manager',
        office: 'Santiago',
        requestedBy: 'kcourson1@va.gov',
        los: 'Assurance',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 9,
        action: 'tristique',
    },
    {
        requestID: '05294ca9-9793-4994-ac7f-a34af47f5261',
        startDateVancancy: '8/17/2022',
        entryDateEmployee: '2/18/2022',
        workerType: 'Socio',
        jobTitle: 'Associate',
        office: 'Santiago',
        requestedBy: 'rchamp2@umich.edu',
        los: 'Assurance',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 3,
        action: 'eu',
    },
    {
        requestID: 'cb174e52-34f2-4784-9cb6-86db77fce732',
        startDateVancancy: '4/10/2022',
        entryDateEmployee: '5/19/2022',
        workerType: 'Regular',
        jobTitle: 'Senior Associate 2',
        office: 'Concepción',
        requestedBy: 'fputterill3@samsung.com',
        los: 'IFS',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 5,
        action: 'amet',
    },
    {
        requestID: '773f3908-3b75-42f6-ab12-e8fda79aff63',
        startDateVancancy: '12/5/2022',
        entryDateEmployee: '5/29/2022',
        workerType: 'Regular',
        jobTitle: 'Partner',
        office: 'Santiago',
        requestedBy: 'wdavidavidovics4@virginia.edu',
        los: 'Advisory',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 4,
        action: 'donec',
    },
    {
        requestID: '370261de-824e-467f-b8e2-4e26cd03d30a',
        startDateVancancy: '5/5/2022',
        entryDateEmployee: '12/11/2022',
        workerType: 'Trainee',
        jobTitle: 'Senior Associate 2',
        office: 'Concepción',
        requestedBy: 'wcurrer5@uol.com.br',
        los: 'IFS',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 9,
        action: 'semper',
    },
    {
        requestID: 'bef02f20-034c-42a2-9b0a-d7371673ea5d',
        startDateVancancy: '11/22/2022',
        entryDateEmployee: '9/2/2022',
        workerType: 'Regular',
        jobTitle: 'Associate',
        office: 'Concepción',
        requestedBy: 'alaborde6@vimeo.com',
        los: 'IFS',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 4,
        action: 'risus',
    },
    {
        requestID: 'a24691d2-59c9-4d95-b5e1-855d31330a3b',
        startDateVancancy: '9/18/2022',
        entryDateEmployee: '8/4/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Senior Associate 2',
        office: 'Concepción',
        requestedBy: 'rchaim7@blinklist.com',
        los: 'Advisory',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Creada',
        totalVacancies: 15,
        action: 'egestas',
    },
    {
        requestID: '43fc1ed4-10e6-404a-b061-83413edb384e',
        startDateVancancy: '8/14/2022',
        entryDateEmployee: '2/15/2022',
        workerType: 'Regular',
        jobTitle: 'Senior Manager',
        office: 'Puerto Montt',
        requestedBy: 'rshakespeare8@cafepress.com',
        los: 'Assurance',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Creada',
        totalVacancies: 11,
        action: 'imperdiet',
    },
    {
        requestID: '42515756-f859-4e87-8376-1c08949b8020',
        startDateVancancy: '6/7/2022',
        entryDateEmployee: '1/24/2022',
        workerType: 'Trainee',
        jobTitle: 'Senior Associate 2',
        office: 'Puerto Montt',
        requestedBy: 'sjowitt9@nhs.uk',
        los: 'Assurance',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 10,
        action: 'quam',
    },
    {
        requestID: '7c3f6454-3f54-455e-b1c9-5d9f9f6ba4bd',
        startDateVancancy: '9/7/2022',
        entryDateEmployee: '3/15/2022',
        workerType: 'Socio',
        jobTitle: 'Associate 2',
        office: 'Santiago',
        requestedBy: 'sdespensera@a8.net',
        los: 'Assurance',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 3,
        action: 'vivamus',
    },
    {
        requestID: '613827cf-f5f1-4900-8d8b-90990a05b5e0',
        startDateVancancy: '10/20/2022',
        entryDateEmployee: '10/21/2022',
        workerType: 'Socio',
        jobTitle: 'Associate',
        office: 'Puerto Montt',
        requestedBy: 'castleyb@si.edu',
        los: 'Advisory',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 8,
        action: 'elementum',
    },
    {
        requestID: '08b55895-c886-401e-9b34-93b82fcc1e9e',
        startDateVancancy: '2/24/2022',
        entryDateEmployee: '12/27/2022',
        workerType: 'Regular',
        jobTitle: 'Associate 2',
        office: 'Santiago',
        requestedBy: 'amortimerc@mac.com',
        los: 'Assurance',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Creada',
        totalVacancies: 6,
        action: 'rhoncus',
    },
    {
        requestID: '4d9dd707-26a3-49f5-8395-babc9bd0c2f3',
        startDateVancancy: '5/12/2022',
        entryDateEmployee: '11/29/2022',
        workerType: 'Regular',
        jobTitle: 'Senior Manager',
        office: 'Concepción',
        requestedBy: 'bmaginnd@homestead.com',
        los: 'Advisory',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 9,
        action: 'mattis',
    },
    {
        requestID: 'ed2fb463-7830-460c-8c0f-16eb208400ac',
        startDateVancancy: '3/2/2022',
        entryDateEmployee: '10/14/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Partner',
        office: 'Concepción',
        requestedBy: 'dstreetone@goo.gl',
        los: 'IFS',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Creada',
        totalVacancies: 3,
        action: 'accumsan',
    },
    {
        requestID: 'db881e68-5122-41b4-b6fa-fbfa8dc07508',
        startDateVancancy: '9/2/2022',
        entryDateEmployee: '5/9/2022',
        workerType: 'Trainee',
        jobTitle: 'Senior Manager',
        office: 'Santiago',
        requestedBy: 'lmcfarlandf@google.ru',
        los: 'Advisory',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 4,
        action: 'amet',
    },
    {
        requestID: '68758b8d-7fbf-4db8-b084-8d2b05286285',
        startDateVancancy: '6/26/2022',
        entryDateEmployee: '7/11/2022',
        workerType: 'Trainee',
        jobTitle: 'Manager',
        office: 'Santiago',
        requestedBy: 'acheving@skype.com',
        los: 'IFS',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 15,
        action: 'non',
    },
    {
        requestID: '53afb9a8-3c30-40b1-bab7-100a70dc3edf',
        startDateVancancy: '9/30/2022',
        entryDateEmployee: '11/8/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Associate 2',
        office: 'Concepción',
        requestedBy: 'vcantuh@cbslocal.com',
        los: 'Advisory',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 12,
        action: 'integer',
    },
    {
        requestID: '4159b200-5653-4da9-a476-b669bb1cead8',
        startDateVancancy: '10/27/2022',
        entryDateEmployee: '6/17/2022',
        workerType: 'Socio',
        jobTitle: 'Manager',
        office: 'Puerto Montt',
        requestedBy: 'irappoporti@blogs.com',
        los: 'Assurance',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 5,
        action: 'placerat',
    },
    {
        requestID: 'f62a2c9b-9ce0-4e74-a89a-ff802b46aae6',
        startDateVancancy: '8/2/2022',
        entryDateEmployee: '5/26/2022',
        workerType: 'Socio',
        jobTitle: 'Partner',
        office: 'Concepción',
        requestedBy: 'clowersonj@engadget.com',
        los: 'Advisory',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 9,
        action: 'vestibulum',
    },
    {
        requestID: '2d6bcf41-8252-4442-a91e-15406b54ae40',
        startDateVancancy: '4/25/2022',
        entryDateEmployee: '3/13/2022',
        workerType: 'Trainee',
        jobTitle: 'Senior Associate 2',
        office: 'Santiago',
        requestedBy: 'dklimochkink@wp.com',
        los: 'IFS',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 12,
        action: 'eget',
    },
    {
        requestID: '70eeb264-fdd1-4a6d-99ab-ed214ab74fa6',
        startDateVancancy: '11/27/2022',
        entryDateEmployee: '4/25/2022',
        workerType: 'Socio',
        jobTitle: 'Associate 2',
        office: 'Concepción',
        requestedBy: 'bnortheyl@ifeng.com',
        los: 'Tax',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 14,
        action: 'dolor',
    },
    {
        requestID: '62048184-36a2-4c08-95c4-17d64e7a78d9',
        startDateVancancy: '3/20/2022',
        entryDateEmployee: '10/2/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Associate 2',
        office: 'Puerto Montt',
        requestedBy: 'lgedlingm@cargocollective.com',
        los: 'IFS',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 1,
        action: 'at',
    },
    {
        requestID: '197d3706-5439-41b5-b0fd-15b7aff8cc35',
        startDateVancancy: '4/8/2022',
        entryDateEmployee: '1/15/2022',
        workerType: 'Regular',
        jobTitle: 'Senior Manager',
        office: 'Concepción',
        requestedBy: 'wfearnn@flickr.com',
        los: 'Tax',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 9,
        action: 'cras',
    },
    {
        requestID: 'dfc10d7d-bbcc-4412-a9b7-9826dfbbba7d',
        startDateVancancy: '11/13/2022',
        entryDateEmployee: '7/4/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Senior Associate 2',
        office: 'Santiago',
        requestedBy: 'agillanio@wikimedia.org',
        los: 'Advisory',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 8,
        action: 'erat',
    },
    {
        requestID: '2750ec64-46e4-4c4e-8304-041475e6e5cb',
        startDateVancancy: '11/17/2022',
        entryDateEmployee: '12/24/2022',
        workerType: 'Regular',
        jobTitle: 'Associate',
        office: 'Concepción',
        requestedBy: 'mpetchellp@dmoz.org',
        los: 'IFS',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 13,
        action: 'congue',
    },
    {
        requestID: '798d503e-1c37-41c0-9520-7972d1aac6a3',
        startDateVancancy: '9/1/2022',
        entryDateEmployee: '2/6/2022',
        workerType: 'Trainee',
        jobTitle: 'Manager',
        office: 'Santiago',
        requestedBy: 'cshingfieldq@vimeo.com',
        los: 'Tax',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 2,
        action: 'non',
    },
    {
        requestID: 'b0defab7-b9f0-4455-84d8-6bed2505386f',
        startDateVancancy: '4/10/2022',
        entryDateEmployee: '10/11/2022',
        workerType: 'Trainee',
        jobTitle: 'Senior Manager',
        office: 'Puerto Montt',
        requestedBy: 'sferronr@narod.ru',
        los: 'Assurance',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 13,
        action: 'ut',
    },
    {
        requestID: '00f2442d-2ae4-4b80-82b8-d0a515fd7616',
        startDateVancancy: '4/26/2022',
        entryDateEmployee: '12/15/2022',
        workerType: 'Trainee',
        jobTitle: 'Senior Manager',
        office: 'Santiago',
        requestedBy: 'nburgyns@ebay.co.uk',
        los: 'Tax',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 10,
        action: 'congue',
    },
    {
        requestID: '7e66eb62-8c3e-45ce-b6d6-9092462d42e2',
        startDateVancancy: '11/16/2022',
        entryDateEmployee: '5/11/2022',
        workerType: 'Regular',
        jobTitle: 'Associate',
        office: 'Concepción',
        requestedBy: 'tcordt@discuz.net',
        los: 'Tax',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 5,
        action: 'libero',
    },
    {
        requestID: '589ffd83-d384-46eb-b2d0-ab91d34e561a',
        startDateVancancy: '11/11/2022',
        entryDateEmployee: '6/2/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Associate',
        office: 'Santiago',
        requestedBy: 'ssaltsbergu@oaic.gov.au',
        los: 'Advisory',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 7,
        action: 'ullamcorper',
    },
    {
        requestID: 'bd699bd4-29be-4f87-a80b-5047a04e64ba',
        startDateVancancy: '10/2/2022',
        entryDateEmployee: '12/31/2022',
        workerType: 'Trainee',
        jobTitle: 'Manager',
        office: 'Puerto Montt',
        requestedBy: 'cfeldbergerv@samsung.com',
        los: 'Tax',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 15,
        action: 'suscipit',
    },
    {
        requestID: '2590b144-ddad-4a65-88f3-2f8db72184ce',
        startDateVancancy: '9/15/2022',
        entryDateEmployee: '7/25/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Senior Associate 2',
        office: 'Santiago',
        requestedBy: 'emctearw@mlb.com',
        los: 'IFS',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 11,
        action: 'quisque',
    },
    {
        requestID: 'a876b801-e6c8-4efa-b3e9-841db2bcc157',
        startDateVancancy: '12/20/2022',
        entryDateEmployee: '12/13/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Associate 2',
        office: 'Concepción',
        requestedBy: 'lheakx@facebook.com',
        los: 'Tax',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 11,
        action: 'orci',
    },
    {
        requestID: 'f4c7a426-a7de-4641-9af4-780bbc6dd6dc',
        startDateVancancy: '7/19/2022',
        entryDateEmployee: '11/22/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Associate',
        office: 'Santiago',
        requestedBy: 'rlethardyy@dmoz.org',
        los: 'Advisory',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 11,
        action: 'in',
    },
    {
        requestID: '5b47cd8d-20f3-490c-be6c-678bafd02977',
        startDateVancancy: '10/19/2022',
        entryDateEmployee: '3/25/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Associate',
        office: 'Concepción',
        requestedBy: 'erudgez@nymag.com',
        los: 'Assurance',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 9,
        action: 'vitae',
    },
    {
        requestID: '512b135d-c6e3-45eb-983c-454a99882b65',
        startDateVancancy: '2/3/2022',
        entryDateEmployee: '4/29/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Manager',
        office: 'Santiago',
        requestedBy: 'tspadaro10@acquirethisname.com',
        los: 'Assurance',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 13,
        action: 'feugiat',
    },
    {
        requestID: 'eea034e8-701d-4983-a70b-6b99b2780f91',
        startDateVancancy: '11/7/2022',
        entryDateEmployee: '1/1/2023',
        workerType: 'Trainee',
        jobTitle: 'Manager',
        office: 'Puerto Montt',
        requestedBy: 'cshelf11@dailymotion.com',
        los: 'Tax',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 2,
        action: 'sit',
    },
    {
        requestID: '7ed6510d-2c9c-4ed0-b5cf-d96aa2ef66e2',
        startDateVancancy: '6/12/2022',
        entryDateEmployee: '3/15/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Senior Manager',
        office: 'Santiago',
        requestedBy: 'fcowen12@fastcompany.com',
        los: 'Tax',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 7,
        action: 'phasellus',
    },
    {
        requestID: '75490e84-ba47-4b15-919e-99ece1fdfc51',
        startDateVancancy: '9/22/2022',
        entryDateEmployee: '4/15/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Senior Manager',
        office: 'Concepción',
        requestedBy: 'bchyuerton13@youtu.be',
        los: 'Assurance',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Creada',
        totalVacancies: 12,
        action: 'donec',
    },
    {
        requestID: '807df1fa-6521-4310-981f-7ef40a78f370',
        startDateVancancy: '10/19/2022',
        entryDateEmployee: '1/8/2022',
        workerType: 'Regular',
        jobTitle: 'Associate',
        office: 'Puerto Montt',
        requestedBy: 'dslopier14@51.la',
        los: 'IFS',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 12,
        action: 'vestibulum',
    },
    {
        requestID: '3777186c-31fb-43be-81f6-0c8fac8e55f2',
        startDateVancancy: '10/20/2022',
        entryDateEmployee: '8/6/2022',
        workerType: 'Socio',
        jobTitle: 'Associate 2',
        office: 'Concepción',
        requestedBy: 'paberkirder15@lycos.com',
        los: 'Assurance',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 4,
        action: 'dictumst',
    },
    {
        requestID: '1d876a96-46ee-4049-9100-12ae1ffea434',
        startDateVancancy: '7/25/2022',
        entryDateEmployee: '6/28/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Senior Associate 2',
        office: 'Puerto Montt',
        requestedBy: 'ddegiorgi16@eepurl.com',
        los: 'Advisory',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 13,
        action: 'blandit',
    },
    {
        requestID: '659e0b1a-38fc-45ba-b2a8-b71b6099e6e0',
        startDateVancancy: '2/10/2022',
        entryDateEmployee: '8/30/2022',
        workerType: 'Trainee',
        jobTitle: 'Partner',
        office: 'Santiago',
        requestedBy: 'iwebby17@wired.com',
        los: 'Assurance',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 3,
        action: 'ipsum',
    },
    {
        requestID: '2ac557ae-e435-43bc-9ea5-a9132eecd183',
        startDateVancancy: '4/19/2022',
        entryDateEmployee: '6/3/2022',
        workerType: 'Trainee',
        jobTitle: 'Senior Manager',
        office: 'Puerto Montt',
        requestedBy: 'dbasant18@marketwatch.com',
        los: 'Tax',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 2,
        action: 'donec',
    },
    {
        requestID: '6b7ef7a3-f277-4512-91d4-28f209c090ac',
        startDateVancancy: '9/2/2022',
        entryDateEmployee: '2/15/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Manager',
        office: 'Santiago',
        requestedBy: 'tblick19@technorati.com',
        los: 'Advisory',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 1,
        action: 'non',
    },
    {
        requestID: 'cc9b46dc-0fb2-4e6a-9792-32e52ccd5ed9',
        startDateVancancy: '1/11/2022',
        entryDateEmployee: '11/5/2022',
        workerType: 'Trainee',
        jobTitle: 'Senior Manager',
        office: 'Concepción',
        requestedBy: 'gstaveley1a@weibo.com',
        los: 'Tax',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Creada',
        totalVacancies: 5,
        action: 'porttitor',
    },
    {
        requestID: '3194c87a-3888-49e6-93e5-078e3a097162',
        startDateVancancy: '4/25/2022',
        entryDateEmployee: '5/26/2022',
        workerType: 'Socio',
        jobTitle: 'Senior Associate 2',
        office: 'Santiago',
        requestedBy: 'pbrinsden1b@dmoz.org',
        los: 'Advisory',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 1,
        action: 'vehicula',
    },
    {
        requestID: 'cb16c090-3523-4fb5-852a-55ab999de474',
        startDateVancancy: '8/24/2022',
        entryDateEmployee: '10/24/2022',
        workerType: 'Trainee',
        jobTitle: 'Senior Associate 2',
        office: 'Concepción',
        requestedBy: 'nmytton1c@ibm.com',
        los: 'Assurance',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 7,
        action: 'porta',
    },
    {
        requestID: '71799bac-f45b-4669-acf4-20c1e0f40f00',
        startDateVancancy: '7/30/2022',
        entryDateEmployee: '11/27/2022',
        workerType: 'Trainee',
        jobTitle: 'Senior Manager',
        office: 'Puerto Montt',
        requestedBy: 'hmedeway1d@slideshare.net',
        los: 'Tax',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 6,
        action: 'aliquam',
    },
    {
        requestID: 'fcd76dd9-a8c6-465c-ae74-31ab2de5dd20',
        startDateVancancy: '8/9/2022',
        entryDateEmployee: '12/8/2022',
        workerType: 'Trainee',
        jobTitle: 'Manager',
        office: 'Puerto Montt',
        requestedBy: 'romullally1e@rambler.ru',
        los: 'Tax',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Creada',
        totalVacancies: 11,
        action: 'platea',
    },
    {
        requestID: '3d2abb51-4892-4d18-bf99-450ae9e330d5',
        startDateVancancy: '9/6/2022',
        entryDateEmployee: '5/23/2022',
        workerType: 'Socio',
        jobTitle: 'Partner',
        office: 'Santiago',
        requestedBy: 'meicke1f@mediafire.com',
        los: 'IFS',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 3,
        action: 'arcu',
    },
    {
        requestID: '0d30f3b4-fd45-4be4-a2ed-17b4b4f6ab60',
        startDateVancancy: '10/6/2022',
        entryDateEmployee: '2/19/2022',
        workerType: 'Trainee',
        jobTitle: 'Senior Manager',
        office: 'Puerto Montt',
        requestedBy: 'lrickell1g@ibm.com',
        los: 'Tax',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 9,
        action: 'id',
    },
    {
        requestID: 'd4f90481-6756-4e50-b86b-d814034dbae1',
        startDateVancancy: '11/10/2022',
        entryDateEmployee: '2/18/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Senior Associate 2',
        office: 'Concepción',
        requestedBy: 'rbeauchamp1h@hp.com',
        los: 'IFS',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 14,
        action: 'vulputate',
    },
    {
        requestID: '1ca6fa88-b703-4706-ab9b-4fd8a1e6a27a',
        startDateVancancy: '5/14/2022',
        entryDateEmployee: '10/26/2022',
        workerType: 'Regular',
        jobTitle: 'Partner',
        office: 'Concepción',
        requestedBy: 'kwhayman1i@earthlink.net',
        los: 'IFS',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 4,
        action: 'dolor',
    },
    {
        requestID: 'a7495cc8-e6a5-4361-8c90-403bb3745706',
        startDateVancancy: '3/12/2022',
        entryDateEmployee: '7/18/2022',
        workerType: 'Trainee',
        jobTitle: 'Associate 2',
        office: 'Santiago',
        requestedBy: 'dbonnett1j@pbs.org',
        los: 'IFS',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 13,
        action: 'risus',
    },
    {
        requestID: '4e209a71-a7ca-4027-a83d-6233a3785e3d',
        startDateVancancy: '1/12/2022',
        entryDateEmployee: '12/16/2022',
        workerType: 'Socio',
        jobTitle: 'Partner',
        office: 'Santiago',
        requestedBy: 'mkeri1k@squidoo.com',
        los: 'Assurance',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 4,
        action: 'interdum',
    },
    {
        requestID: 'd308f317-98c6-4be7-a582-e1834feef867',
        startDateVancancy: '3/23/2022',
        entryDateEmployee: '8/22/2022',
        workerType: 'Trainee',
        jobTitle: 'Associate 2',
        office: 'Santiago',
        requestedBy: 'mgelletly1l@last.fm',
        los: 'Assurance',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Creada',
        totalVacancies: 7,
        action: 'aliquet',
    },
    {
        requestID: 'fb622b07-d06f-4158-9ba6-aebab831a5ca',
        startDateVancancy: '7/15/2022',
        entryDateEmployee: '9/21/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Associate 2',
        office: 'Santiago',
        requestedBy: 'dscarf1m@exblog.jp',
        los: 'Advisory',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 5,
        action: 'et',
    },
    {
        requestID: '83456b38-9b3f-412b-9d35-db28b3f22ff7',
        startDateVancancy: '5/22/2022',
        entryDateEmployee: '7/2/2022',
        workerType: 'Regular',
        jobTitle: 'Associate',
        office: 'Concepción',
        requestedBy: 'wminger1n@ustream.tv',
        los: 'Advisory',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 5,
        action: 'quam',
    },
    {
        requestID: 'fc7b5fe6-a4cb-4395-a492-a9e737951f2c',
        startDateVancancy: '10/23/2022',
        entryDateEmployee: '11/4/2022',
        workerType: 'Trainee',
        jobTitle: 'Manager',
        office: 'Santiago',
        requestedBy: 'mgoullee1o@blinklist.com',
        los: 'Tax',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 10,
        action: 'odio',
    },
    {
        requestID: '9dbc3433-11e2-40b4-8c8c-318543b49e45',
        startDateVancancy: '10/23/2022',
        entryDateEmployee: '8/26/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Associate',
        office: 'Puerto Montt',
        requestedBy: 'glevings1p@businessinsider.com',
        los: 'Advisory',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 3,
        action: 'in',
    },
    {
        requestID: '9192f9c0-751d-4fd9-9f0c-2a9014a3e0b0',
        startDateVancancy: '9/20/2022',
        entryDateEmployee: '12/8/2022',
        workerType: 'Trainee',
        jobTitle: 'Partner',
        office: 'Santiago',
        requestedBy: 'apee1q@earthlink.net',
        los: 'Tax',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 6,
        action: 'augue',
    },
    {
        requestID: '4d25886b-2c54-41bf-a141-86f6c78df04d',
        startDateVancancy: '12/8/2022',
        entryDateEmployee: '12/9/2022',
        workerType: 'Socio',
        jobTitle: 'Associate 2',
        office: 'Santiago',
        requestedBy: 'dchancelier1r@dell.com',
        los: 'IFS',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Creada',
        totalVacancies: 3,
        action: 'justo',
    },
    {
        requestID: 'fb368cbb-0761-4132-b9b9-cd3839d88b33',
        startDateVancancy: '3/4/2022',
        entryDateEmployee: '7/1/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Associate 2',
        office: 'Santiago',
        requestedBy: 'eprobet1s@google.cn',
        los: 'Advisory',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 4,
        action: 'enim',
    },
    {
        requestID: 'ea270fa4-3d25-4a3a-a753-3a48cf873613',
        startDateVancancy: '11/22/2022',
        entryDateEmployee: '5/26/2022',
        workerType: 'Socio',
        jobTitle: 'Manager',
        office: 'Puerto Montt',
        requestedBy: 'jsummerrell1t@desdev.cn',
        los: 'Assurance',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 10,
        action: 'id',
    },
    {
        requestID: '52c0d65c-135c-4a0c-bfa3-c93bd2681842',
        startDateVancancy: '11/17/2022',
        entryDateEmployee: '11/2/2022',
        workerType: 'Socio',
        jobTitle: 'Associate',
        office: 'Concepción',
        requestedBy: 'lleare1u@hubpages.com',
        los: 'Advisory',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 2,
        action: 'nullam',
    },
    {
        requestID: 'ebb5665f-c78d-40f5-8ad7-eaea184c4ea8',
        startDateVancancy: '2/20/2022',
        entryDateEmployee: '2/18/2022',
        workerType: 'Trainee',
        jobTitle: 'Associate 2',
        office: 'Santiago',
        requestedBy: 'efripps1v@noaa.gov',
        los: 'Tax',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 10,
        action: 'ante',
    },
    {
        requestID: '8468c48c-9f21-44e5-9007-caf02be71e75',
        startDateVancancy: '2/28/2022',
        entryDateEmployee: '9/10/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Senior Associate 2',
        office: 'Santiago',
        requestedBy: 'ehuxstep1w@japanpost.jp',
        los: 'IFS',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 3,
        action: 'quis',
    },
    {
        requestID: '5e1aeaea-b2eb-47ee-935d-aafff166d0bc',
        startDateVancancy: '12/5/2022',
        entryDateEmployee: '9/9/2022',
        workerType: 'Trainee',
        jobTitle: 'Partner',
        office: 'Santiago',
        requestedBy: 'aabdy1x@smh.com.au',
        los: 'Assurance',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 5,
        action: 'odio',
    },
    {
        requestID: '5ac437da-c615-4eef-81d3-84c45b7a2d5b',
        startDateVancancy: '2/14/2022',
        entryDateEmployee: '1/16/2022',
        workerType: 'Socio',
        jobTitle: 'Associate',
        office: 'Concepción',
        requestedBy: 'ysketh1y@ucla.edu',
        los: 'Advisory',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Creada',
        totalVacancies: 5,
        action: 'etiam',
    },
    {
        requestID: '0663b776-6d37-4f26-822c-ba3d90117ed9',
        startDateVancancy: '2/16/2022',
        entryDateEmployee: '2/14/2022',
        workerType: 'Socio',
        jobTitle: 'Senior Manager',
        office: 'Concepción',
        requestedBy: 'nkeeble1z@eepurl.com',
        los: 'Assurance',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Creada',
        totalVacancies: 5,
        action: 'consequat',
    },
    {
        requestID: 'b016b619-6528-434b-a9ba-3fb1108307ab',
        startDateVancancy: '4/17/2022',
        entryDateEmployee: '8/25/2022',
        workerType: 'Socio',
        jobTitle: 'Partner',
        office: 'Santiago',
        requestedBy: 'showieson20@omniture.com',
        los: 'IFS',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 2,
        action: 'diam',
    },
    {
        requestID: '0b486fa6-64f9-4833-8947-ca407d0d7447',
        startDateVancancy: '11/12/2022',
        entryDateEmployee: '1/17/2022',
        workerType: 'Socio',
        jobTitle: 'Associate',
        office: 'Concepción',
        requestedBy: 'ktheyer21@reuters.com',
        los: 'Advisory',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Creada',
        totalVacancies: 7,
        action: 'ligula',
    },
    {
        requestID: 'd4f0e84e-092f-4016-b8ce-ecd642e7da73',
        startDateVancancy: '8/14/2022',
        entryDateEmployee: '5/26/2022',
        workerType: 'Socio',
        jobTitle: 'Senior Associate 2',
        office: 'Concepción',
        requestedBy: 'ewinterton22@networksolutions.com',
        los: 'Assurance',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 6,
        action: 'ut',
    },
    {
        requestID: '6d1b375a-0ada-4cb8-a8db-9a34b5ab16b2',
        startDateVancancy: '8/30/2022',
        entryDateEmployee: '11/22/2022',
        workerType: 'Trainee',
        jobTitle: 'Partner',
        office: 'Santiago',
        requestedBy: 'wrojahn23@arstechnica.com',
        los: 'Tax',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Creada',
        totalVacancies: 14,
        action: 'neque',
    },
    {
        requestID: '1dc96bbf-ebdb-48ab-b690-35d547b24733',
        startDateVancancy: '9/3/2022',
        entryDateEmployee: '7/6/2022',
        workerType: 'Trainee',
        jobTitle: 'Associate 2',
        office: 'Concepción',
        requestedBy: 'ljuniper24@google.co.jp',
        los: 'Advisory',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 12,
        action: 'vitae',
    },
    {
        requestID: '8448d11a-2796-4a03-a87c-0b0abb41b8e1',
        startDateVancancy: '10/17/2022',
        entryDateEmployee: '9/1/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Manager',
        office: 'Santiago',
        requestedBy: 'sgarard25@google.es',
        los: 'Advisory',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 6,
        action: 'tincidunt',
    },
    {
        requestID: '0fb76e02-c3bd-4bc6-8a14-8f5fd0e44e76',
        startDateVancancy: '4/3/2022',
        entryDateEmployee: '10/12/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Senior Associate 2',
        office: 'Concepción',
        requestedBy: 'vdibartolomeo26@fc2.com',
        los: 'Tax',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 14,
        action: 'quam',
    },
    {
        requestID: '1612986c-e45e-4098-b7f5-e0b85d9fc987',
        startDateVancancy: '10/5/2022',
        entryDateEmployee: '2/17/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Senior Manager',
        office: 'Santiago',
        requestedBy: 'cbrittain27@google.ru',
        los: 'Assurance',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 1,
        action: 'odio',
    },
    {
        requestID: 'e28d6aeb-2ad8-47d8-9c95-e1ae2c5d8da4',
        startDateVancancy: '12/23/2022',
        entryDateEmployee: '7/21/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Associate 2',
        office: 'Puerto Montt',
        requestedBy: 'nlangthorne28@github.io',
        los: 'Tax',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 2,
        action: 'molestie',
    },
    {
        requestID: '4c82197f-c74f-47a1-8618-ef675ff463ae',
        startDateVancancy: '6/29/2022',
        entryDateEmployee: '2/18/2022',
        workerType: 'Socio',
        jobTitle: 'Senior Manager',
        office: 'Concepción',
        requestedBy: 'bfenney29@ucoz.com',
        los: 'Tax',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Creada',
        totalVacancies: 5,
        action: 'nisl',
    },
    {
        requestID: '404a207f-013e-4352-a18d-f782b0f7713c',
        startDateVancancy: '11/14/2022',
        entryDateEmployee: '3/22/2022',
        workerType: 'Regular',
        jobTitle: 'Senior Manager',
        office: 'Santiago',
        requestedBy: 'bbertolaccini2a@ox.ac.uk',
        los: 'Tax',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 6,
        action: 'vivamus',
    },
    {
        requestID: 'd8064c62-e968-4d69-9c8d-88c09974b8ac',
        startDateVancancy: '9/6/2022',
        entryDateEmployee: '9/16/2022',
        workerType: 'Socio',
        jobTitle: 'Senior Manager',
        office: 'Puerto Montt',
        requestedBy: 'atimbs2b@paginegialle.it',
        los: 'IFS',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 6,
        action: 'eu',
    },
    {
        requestID: '83939e75-2bc8-4a8f-bca4-89ada68a761c',
        startDateVancancy: '4/24/2022',
        entryDateEmployee: '4/12/2022',
        workerType: 'Regular',
        jobTitle: 'Senior Manager',
        office: 'Concepción',
        requestedBy: 'lbarehead2c@jalbum.net',
        los: 'IFS',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 7,
        action: 'est',
    },
    {
        requestID: 'bff6e1ba-6894-43d8-841f-89e05c671e54',
        startDateVancancy: '3/9/2022',
        entryDateEmployee: '5/5/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Partner',
        office: 'Santiago',
        requestedBy: 'abernot2d@joomla.org',
        los: 'IFS',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 12,
        action: 'faucibus',
    },
    {
        requestID: 'eca3657a-b23e-465f-a952-a669d95c60d7',
        startDateVancancy: '7/8/2022',
        entryDateEmployee: '2/15/2022',
        workerType: 'Trainee',
        jobTitle: 'Partner',
        office: 'Concepción',
        requestedBy: 'mbogays2e@google.fr',
        los: 'Advisory',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 8,
        action: 'quis',
    },
    {
        requestID: 'be0d9368-e597-4eb0-80c1-8b39e29bb30f',
        startDateVancancy: '10/1/2022',
        entryDateEmployee: '9/1/2022',
        workerType: 'Regular',
        jobTitle: 'Senior Associate 2',
        office: 'Concepción',
        requestedBy: 'fniblo2f@dropbox.com',
        los: 'Advisory',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 10,
        action: 'amet',
    },
    {
        requestID: '4d66e308-e4f1-4440-9cb5-c9c886cc533a',
        startDateVancancy: '2/1/2022',
        entryDateEmployee: '8/25/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Senior Associate 2',
        office: 'Concepción',
        requestedBy: 'cennew2g@go.com',
        los: 'Tax',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 8,
        action: 'aliquam',
    },
    {
        requestID: '2c014343-9910-43c9-86e6-b8107fba2430',
        startDateVancancy: '11/3/2022',
        entryDateEmployee: '12/10/2022',
        workerType: 'Regular',
        jobTitle: 'Associate 2',
        office: 'Puerto Montt',
        requestedBy: 'rmessruther2h@example.com',
        los: 'IFS',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 3,
        action: 'duis',
    },
    {
        requestID: '22566a7d-91f9-40ff-bf77-1dd6403c51c5',
        startDateVancancy: '8/20/2022',
        entryDateEmployee: '12/22/2022',
        workerType: 'Regular',
        jobTitle: 'Associate 2',
        office: 'Santiago',
        requestedBy: 'bcuchey2i@addtoany.com',
        los: 'IFS',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 9,
        action: 'pede',
    },
    {
        requestID: '546d53fd-294d-4118-b559-977fbf5b3964',
        startDateVancancy: '8/10/2022',
        entryDateEmployee: '7/25/2022',
        workerType: 'Trainee',
        jobTitle: 'Associate 2',
        office: 'Concepción',
        requestedBy: 'mhuster2j@ftc.gov',
        los: 'IFS',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 14,
        action: 'et',
    },
    {
        requestID: 'e92b64a9-ec0c-4503-a538-8e5b9ae46634',
        startDateVancancy: '5/12/2022',
        entryDateEmployee: '6/14/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Associate',
        office: 'Santiago',
        requestedBy: 'dcawdery2k@webnode.com',
        los: 'Advisory',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 10,
        action: 'sem',
    },
    {
        requestID: 'f69aebc0-08f4-4f77-8b04-f37ce6f15a9c',
        startDateVancancy: '9/26/2022',
        entryDateEmployee: '11/9/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Associate 2',
        office: 'Santiago',
        requestedBy: 'dmcaw2l@yellowpages.com',
        los: 'Tax',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 5,
        action: 'dictumst',
    },
    {
        requestID: '582d4d37-d71a-4207-bd77-b50d05074665',
        startDateVancancy: '3/22/2022',
        entryDateEmployee: '6/5/2022',
        workerType: 'Trainee',
        jobTitle: 'Partner',
        office: 'Puerto Montt',
        requestedBy: 'ptucker2m@amazonaws.com',
        los: 'IFS',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 8,
        action: 'nascetur',
    },
    {
        requestID: '042cce52-4d5c-462b-8286-e24273228b16',
        startDateVancancy: '12/28/2022',
        entryDateEmployee: '4/2/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Associate',
        office: 'Puerto Montt',
        requestedBy: 'abrookhouse2n@ed.gov',
        los: 'Tax',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 5,
        action: 'non',
    },
    {
        requestID: '3a400078-b985-4594-9c92-b872166b8921',
        startDateVancancy: '2/16/2022',
        entryDateEmployee: '3/3/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Senior Associate 2',
        office: 'Santiago',
        requestedBy: 'rgovinlock2o@woothemes.com',
        los: 'IFS',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 15,
        action: 'sed',
    },
    {
        requestID: '549b02cb-1276-4b34-ad5e-c6357ac0c714',
        startDateVancancy: '10/14/2022',
        entryDateEmployee: '3/18/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Senior Associate 2',
        office: 'Santiago',
        requestedBy: 'bhouldin2p@friendfeed.com',
        los: 'Tax',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 1,
        action: 'ipsum',
    },
    {
        requestID: '56f18b48-3248-4279-b2be-d97df5b0fe60',
        startDateVancancy: '11/13/2022',
        entryDateEmployee: '3/11/2022',
        workerType: 'Regular',
        jobTitle: 'Associate',
        office: 'Santiago',
        requestedBy: 'mdellenbroker2q@noaa.gov',
        los: 'IFS',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 7,
        action: 'justo',
    },
    {
        requestID: 'b265dd14-fe7a-4808-8ec5-9bb2485ba689',
        startDateVancancy: '12/21/2022',
        entryDateEmployee: '10/21/2022',
        workerType: 'Socio',
        jobTitle: 'Senior Manager',
        office: 'Santiago',
        requestedBy: 'lmousby2r@foxnews.com',
        los: 'IFS',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 3,
        action: 'mauris',
    },
    {
        requestID: 'a29e3d44-f856-4034-8542-88fd7b0594ef',
        startDateVancancy: '9/10/2022',
        entryDateEmployee: '5/30/2022',
        workerType: 'Trainee',
        jobTitle: 'Senior Associate 2',
        office: 'Santiago',
        requestedBy: 'mgabriel2s@fotki.com',
        los: 'Assurance',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 4,
        action: 'nisi',
    },
    {
        requestID: 'fa542b54-9b6e-488d-8f5d-43293c3c5ce9',
        startDateVancancy: '3/8/2022',
        entryDateEmployee: '5/1/2022',
        workerType: 'Trainee',
        jobTitle: 'Manager',
        office: 'Santiago',
        requestedBy: 'hleacock2t@newsvine.com',
        los: 'Tax',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 8,
        action: 'arcu',
    },
    {
        requestID: '04249cff-cc7b-4e18-bdb2-ae3785e056bc',
        startDateVancancy: '2/18/2022',
        entryDateEmployee: '8/11/2022',
        workerType: 'Trainee',
        jobTitle: 'Associate 2',
        office: 'Concepción',
        requestedBy: 'rkettridge2u@example.com',
        los: 'Tax',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Creada',
        totalVacancies: 8,
        action: 'et',
    },
    {
        requestID: '5717688b-d339-44fd-a4af-0cd65d1df4c0',
        startDateVancancy: '12/9/2022',
        entryDateEmployee: '9/29/2022',
        workerType: 'Regular',
        jobTitle: 'Associate 2',
        office: 'Puerto Montt',
        requestedBy: 'cterrett2v@smugmug.com',
        los: 'Advisory',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 4,
        action: 'etiam',
    },
    {
        requestID: 'f982b6a6-fd9c-42a6-a59a-7477e942b9e1',
        startDateVancancy: '12/30/2022',
        entryDateEmployee: '12/14/2022',
        workerType: 'Trainee',
        jobTitle: 'Manager',
        office: 'Concepción',
        requestedBy: 'igaish2w@umn.edu',
        los: 'IFS',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 3,
        action: 'odio',
    },
    {
        requestID: '1db72b10-baf7-402b-a27b-c24a967dab8c',
        startDateVancancy: '9/7/2022',
        entryDateEmployee: '6/18/2022',
        workerType: 'Trainee',
        jobTitle: 'Senior Manager',
        office: 'Concepción',
        requestedBy: 'kotterwell2x@uiuc.edu',
        los: 'IFS',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 8,
        action: 'proin',
    },
    {
        requestID: 'b718b16a-daee-4b9e-94d1-7694ced4edc8',
        startDateVancancy: '7/10/2022',
        entryDateEmployee: '1/9/2022',
        workerType: 'Socio',
        jobTitle: 'Senior Manager',
        office: 'Puerto Montt',
        requestedBy: 'eglaysher2y@msn.com',
        los: 'Advisory',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 3,
        action: 'tristique',
    },
    {
        requestID: '769db983-3f56-4308-ba22-864905c129bc',
        startDateVancancy: '1/28/2022',
        entryDateEmployee: '3/31/2022',
        workerType: 'Trainee',
        jobTitle: 'Associate',
        office: 'Concepción',
        requestedBy: 'dtrounce2z@hud.gov',
        los: 'Assurance',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 5,
        action: 'iaculis',
    },
    {
        requestID: 'ca3070a0-352e-4aed-b0b0-bde0cf56edb9',
        startDateVancancy: '4/25/2022',
        entryDateEmployee: '7/22/2022',
        workerType: 'Socio',
        jobTitle: 'Senior Associate 2',
        office: 'Concepción',
        requestedBy: 'dschlagman30@webeden.co.uk',
        los: 'Assurance',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 15,
        action: 'pede',
    },
    {
        requestID: 'c1c9d0b7-b7fc-4cc3-a3da-065082f17cde',
        startDateVancancy: '7/25/2022',
        entryDateEmployee: '2/26/2022',
        workerType: 'Trainee',
        jobTitle: 'Associate 2',
        office: 'Santiago',
        requestedBy: 'gtuting31@washingtonpost.com',
        los: 'Advisory',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 9,
        action: 'interdum',
    },
    {
        requestID: 'a7909e18-d981-48a3-bb41-14f464b0d670',
        startDateVancancy: '5/5/2022',
        entryDateEmployee: '3/16/2022',
        workerType: 'Socio',
        jobTitle: 'Associate',
        office: 'Concepción',
        requestedBy: 'lsanten32@go.com',
        los: 'Assurance',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 6,
        action: 'semper',
    },
    {
        requestID: 'e528e13a-ceaf-4860-9dd7-3e883e60005c',
        startDateVancancy: '7/3/2022',
        entryDateEmployee: '7/2/2022',
        workerType: 'Socio',
        jobTitle: 'Senior Manager',
        office: 'Concepción',
        requestedBy: 'dpittendreigh33@goo.ne.jp',
        los: 'Advisory',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 7,
        action: 'a',
    },
    {
        requestID: 'ac39f830-437b-4ec5-81ac-c9e74b9deda3',
        startDateVancancy: '12/17/2022',
        entryDateEmployee: '9/30/2022',
        workerType: 'Regular',
        jobTitle: 'Senior Associate 2',
        office: 'Santiago',
        requestedBy: 'smckeller34@smh.com.au',
        los: 'Advisory',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 15,
        action: 'volutpat',
    },
    {
        requestID: 'ee06ae81-72d8-4ff0-ac53-f331ab301412',
        startDateVancancy: '11/11/2022',
        entryDateEmployee: '3/9/2022',
        workerType: 'Trainee',
        jobTitle: 'Manager',
        office: 'Concepción',
        requestedBy: 'bteague35@merriam-webster.com',
        los: 'Assurance',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 15,
        action: 'ultrices',
    },
    {
        requestID: '1e4b1f18-188e-447a-b94f-9d342bf40e38',
        startDateVancancy: '3/19/2022',
        entryDateEmployee: '5/14/2022',
        workerType: 'Trainee',
        jobTitle: 'Manager',
        office: 'Concepción',
        requestedBy: 'ckillshaw36@last.fm',
        los: 'Assurance',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 15,
        action: 'tincidunt',
    },
    {
        requestID: '30b5e845-4cfd-4b09-b573-2185161d7772',
        startDateVancancy: '10/8/2022',
        entryDateEmployee: '5/23/2022',
        workerType: 'Trainee',
        jobTitle: 'Manager',
        office: 'Puerto Montt',
        requestedBy: 'tgeipel37@tripadvisor.com',
        los: 'IFS',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 4,
        action: 'placerat',
    },
    {
        requestID: '9b87cf42-946f-4e4d-985f-62b076e1119d',
        startDateVancancy: '7/9/2022',
        entryDateEmployee: '5/21/2022',
        workerType: 'Trainee',
        jobTitle: 'Senior Associate 2',
        office: 'Santiago',
        requestedBy: 'pvousden38@uol.com.br',
        los: 'Advisory',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Creada',
        totalVacancies: 1,
        action: 'dui',
    },
    {
        requestID: '93ccbfd7-8ac1-4f28-bdc3-f39e45dddcc5',
        startDateVancancy: '3/11/2022',
        entryDateEmployee: '6/29/2022',
        workerType: 'Socio',
        jobTitle: 'Associate',
        office: 'Concepción',
        requestedBy: 'rodunniom39@omniture.com',
        los: 'IFS',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 14,
        action: 'morbi',
    },
    {
        requestID: '3c63f56b-fc2e-4339-b28e-13a84c7ba1a6',
        startDateVancancy: '1/7/2022',
        entryDateEmployee: '2/12/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Manager',
        office: 'Puerto Montt',
        requestedBy: 'lnegro3a@psu.edu',
        los: 'IFS',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 13,
        action: 'aliquet',
    },
    {
        requestID: '3d3629d2-0482-4b48-83b5-b59dc1e1ca09',
        startDateVancancy: '7/10/2022',
        entryDateEmployee: '3/28/2022',
        workerType: 'Regular',
        jobTitle: 'Associate',
        office: 'Puerto Montt',
        requestedBy: 'dhellyer3b@tinyurl.com',
        los: 'Advisory',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 11,
        action: 'morbi',
    },
    {
        requestID: 'f8027efc-dff3-4ab4-b46e-4e6fe372497b',
        startDateVancancy: '5/23/2022',
        entryDateEmployee: '7/21/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Manager',
        office: 'Puerto Montt',
        requestedBy: 'jfarfoot3c@mapquest.com',
        los: 'Advisory',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 2,
        action: 'mattis',
    },
    {
        requestID: '3d9cef74-2911-4aa4-976d-6bef17b5f0a4',
        startDateVancancy: '6/3/2022',
        entryDateEmployee: '10/21/2022',
        workerType: 'Socio',
        jobTitle: 'Manager',
        office: 'Concepción',
        requestedBy: 'lkenewell3d@narod.ru',
        los: 'IFS',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 11,
        action: 'amet',
    },
    {
        requestID: '89c62fed-361f-4ed4-a9ec-4dc78affa22a',
        startDateVancancy: '3/7/2022',
        entryDateEmployee: '11/1/2022',
        workerType: 'Socio',
        jobTitle: 'Manager',
        office: 'Concepción',
        requestedBy: 'wcraddock3e@goodreads.com',
        los: 'Advisory',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 12,
        action: 'odio',
    },
    {
        requestID: '64972b18-2710-402b-ba16-0337609a7e4a',
        startDateVancancy: '2/1/2022',
        entryDateEmployee: '11/21/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Manager',
        office: 'Concepción',
        requestedBy: 'rciepluch3f@wsj.com',
        los: 'IFS',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 15,
        action: 'vivamus',
    },
    {
        requestID: '1b04f103-9c14-4bd1-a5b1-3be0337bb348',
        startDateVancancy: '9/30/2022',
        entryDateEmployee: '7/31/2022',
        workerType: 'Trainee',
        jobTitle: 'Senior Manager',
        office: 'Concepción',
        requestedBy: 'mtwoohy3g@comsenz.com',
        los: 'Tax',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 5,
        action: 'pulvinar',
    },
    {
        requestID: '78df0e99-c769-4213-a441-8f5a66bfadfd',
        startDateVancancy: '3/22/2022',
        entryDateEmployee: '2/23/2022',
        workerType: 'Trainee',
        jobTitle: 'Senior Manager',
        office: 'Santiago',
        requestedBy: 'gsculley3h@yellowpages.com',
        los: 'IFS',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 4,
        action: 'nulla',
    },
    {
        requestID: 'b1dcdf33-e59b-4237-bf01-611cc843f23e',
        startDateVancancy: '9/16/2022',
        entryDateEmployee: '4/27/2022',
        workerType: 'Socio',
        jobTitle: 'Partner',
        office: 'Puerto Montt',
        requestedBy: 'kkibel3i@google.co.jp',
        los: 'Assurance',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 2,
        action: 'donec',
    },
    {
        requestID: 'b7ce709f-fce6-49a8-8842-42951da4a4d7',
        startDateVancancy: '9/17/2022',
        entryDateEmployee: '12/15/2022',
        workerType: 'Trainee',
        jobTitle: 'Manager',
        office: 'Santiago',
        requestedBy: 'rwhyte3j@weebly.com',
        los: 'Tax',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Creada',
        totalVacancies: 7,
        action: 'a',
    },
    {
        requestID: '390bf6dc-ca93-42a5-bcef-e66d5c2782be',
        startDateVancancy: '6/12/2022',
        entryDateEmployee: '11/26/2022',
        workerType: 'Regular',
        jobTitle: 'Senior Manager',
        office: 'Puerto Montt',
        requestedBy: 'ngimblet3k@prlog.org',
        los: 'Advisory',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 14,
        action: 'vivamus',
    },
    {
        requestID: '04776853-0476-445c-b1d0-08fd1b7f0017',
        startDateVancancy: '12/17/2022',
        entryDateEmployee: '10/15/2022',
        workerType: 'Trainee',
        jobTitle: 'Partner',
        office: 'Concepción',
        requestedBy: 'rvanhove3l@addthis.com',
        los: 'Tax',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 4,
        action: 'euismod',
    },
    {
        requestID: '0bb36f88-a41b-472c-9e87-b73ee1eff8d4',
        startDateVancancy: '11/28/2022',
        entryDateEmployee: '7/1/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Manager',
        office: 'Santiago',
        requestedBy: 'dcodron3m@dot.gov',
        los: 'Advisory',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 12,
        action: 'habitasse',
    },
    {
        requestID: '8dd3cd0a-79ba-4d4f-a953-2136750b0277',
        startDateVancancy: '5/10/2022',
        entryDateEmployee: '1/31/2022',
        workerType: 'Regular',
        jobTitle: 'Associate',
        office: 'Santiago',
        requestedBy: 'agladdifh3n@opera.com',
        los: 'Tax',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 8,
        action: 'sociis',
    },
    {
        requestID: '85861a4f-5d1c-44b7-bc20-09fd042423e3',
        startDateVancancy: '5/15/2022',
        entryDateEmployee: '3/10/2022',
        workerType: 'Trainee',
        jobTitle: 'Senior Associate 2',
        office: 'Concepción',
        requestedBy: 'blikly3o@google.nl',
        los: 'Advisory',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 9,
        action: 'luctus',
    },
    {
        requestID: '4246b432-5bf3-447f-98d9-8a7521394393',
        startDateVancancy: '1/8/2022',
        entryDateEmployee: '7/7/2022',
        workerType: 'Regular',
        jobTitle: 'Associate',
        office: 'Puerto Montt',
        requestedBy: 'doglessane3p@economist.com',
        los: 'Assurance',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Creada',
        totalVacancies: 4,
        action: 'ultrices',
    },
    {
        requestID: 'feee7b29-d3fe-45fe-b882-bc4ec6ef68b9',
        startDateVancancy: '9/8/2022',
        entryDateEmployee: '9/17/2022',
        workerType: 'Trainee',
        jobTitle: 'Partner',
        office: 'Puerto Montt',
        requestedBy: 'swike3q@pagesperso-orange.fr',
        los: 'IFS',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 6,
        action: 'non',
    },
    {
        requestID: '989ba3b7-d608-448d-ac09-6cc4b33f6a93',
        startDateVancancy: '8/11/2022',
        entryDateEmployee: '10/27/2022',
        workerType: 'Socio',
        jobTitle: 'Manager',
        office: 'Concepción',
        requestedBy: 'odawidowsky3r@qq.com',
        los: 'IFS',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 5,
        action: 'in',
    },
    {
        requestID: '4a33a98a-2dd4-4361-9d0f-6faa356b2e23',
        startDateVancancy: '9/3/2022',
        entryDateEmployee: '1/19/2022',
        workerType: 'Regular',
        jobTitle: 'Manager',
        office: 'Santiago',
        requestedBy: 'srubinivitz3s@weibo.com',
        los: 'Advisory',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Creada',
        totalVacancies: 1,
        action: 'consequat',
    },
    {
        requestID: 'a763dd4b-6b47-4d33-819f-9e420528e4f4',
        startDateVancancy: '5/6/2022',
        entryDateEmployee: '3/29/2022',
        workerType: 'Socio',
        jobTitle: 'Associate',
        office: 'Concepción',
        requestedBy: 'jchiplen3t@salon.com',
        los: 'Tax',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 13,
        action: 'lacinia',
    },
    {
        requestID: 'bd92d89a-54a8-44db-8dc1-2dfa73ff09d1',
        startDateVancancy: '10/2/2022',
        entryDateEmployee: '2/4/2022',
        workerType: 'Socio',
        jobTitle: 'Associate',
        office: 'Concepción',
        requestedBy: 'rharbidge3u@engadget.com',
        los: 'Assurance',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 15,
        action: 'mus',
    },
    {
        requestID: '0cf04b37-0560-489c-a5ed-e3d90a7ff3d7',
        startDateVancancy: '6/19/2022',
        entryDateEmployee: '9/10/2022',
        workerType: 'Trainee',
        jobTitle: 'Partner',
        office: 'Puerto Montt',
        requestedBy: 'astockford3v@cnet.com',
        los: 'Assurance',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 8,
        action: 'lacinia',
    },
    {
        requestID: '147aef3d-3d2c-4360-bd76-c522cecaf6c4',
        startDateVancancy: '1/25/2022',
        entryDateEmployee: '9/14/2022',
        workerType: 'Regular',
        jobTitle: 'Senior Manager',
        office: 'Santiago',
        requestedBy: 'cdumsday3w@amazon.com',
        los: 'Assurance',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 8,
        action: 'hac',
    },
    {
        requestID: '9714a8a9-85f6-4196-87db-b39c046841f2',
        startDateVancancy: '3/16/2022',
        entryDateEmployee: '9/26/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Associate',
        office: 'Puerto Montt',
        requestedBy: 'abeasleigh3x@google.cn',
        los: 'IFS',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 4,
        action: 'ut',
    },
    {
        requestID: '8be9fed4-8f2c-43b9-a776-615f42d45527',
        startDateVancancy: '10/31/2022',
        entryDateEmployee: '1/25/2022',
        workerType: 'Trainee',
        jobTitle: 'Associate',
        office: 'Santiago',
        requestedBy: 'cpinilla3y@ameblo.jp',
        los: 'Assurance',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Creada',
        totalVacancies: 10,
        action: 'scelerisque',
    },
    {
        requestID: '1f4f8102-b439-4c02-bbb4-351dfa2a7806',
        startDateVancancy: '9/10/2022',
        entryDateEmployee: '4/8/2022',
        workerType: 'Socio',
        jobTitle: 'Associate 2',
        office: 'Concepción',
        requestedBy: 'zdargie3z@tinypic.com',
        los: 'Advisory',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 13,
        action: 'vulputate',
    },
    {
        requestID: '637040ee-63a2-4783-89ca-e931c78bf2b3',
        startDateVancancy: '4/1/2022',
        entryDateEmployee: '1/4/2023',
        workerType: 'Socio',
        jobTitle: 'Senior Associate 2',
        office: 'Concepción',
        requestedBy: 'lpotten40@reuters.com',
        los: 'Tax',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 11,
        action: 'quam',
    },
    {
        requestID: 'd13cc36e-072e-494b-b96b-c3cc3cb2978c',
        startDateVancancy: '9/22/2022',
        entryDateEmployee: '10/13/2022',
        workerType: 'Socio',
        jobTitle: 'Associate',
        office: 'Puerto Montt',
        requestedBy: 'kgommowe41@so-net.ne.jp',
        los: 'Advisory',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Creada',
        totalVacancies: 7,
        action: 'aliquam',
    },
    {
        requestID: 'f47f6bbf-76aa-4735-b6f4-1b90d2d5ec94',
        startDateVancancy: '11/24/2022',
        entryDateEmployee: '5/30/2022',
        workerType: 'Trainee',
        jobTitle: 'Manager',
        office: 'Puerto Montt',
        requestedBy: 'dmoscone42@dagondesign.com',
        los: 'IFS',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 11,
        action: 'in',
    },
    {
        requestID: '2308657b-d5e3-4991-8d9f-1e54553976ca',
        startDateVancancy: '4/30/2022',
        entryDateEmployee: '6/6/2022',
        workerType: 'Socio',
        jobTitle: 'Associate 2',
        office: 'Concepción',
        requestedBy: 'eshipway43@spiegel.de',
        los: 'Tax',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 9,
        action: 'platea',
    },
    {
        requestID: '9bce6bf8-39c2-4f7b-aeda-88074fed7d4a',
        startDateVancancy: '11/23/2022',
        entryDateEmployee: '1/28/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Associate',
        office: 'Santiago',
        requestedBy: 'bshire44@hao123.com',
        los: 'IFS',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 15,
        action: 'neque',
    },
    {
        requestID: '8c90acc0-9f5a-4585-ab59-ceaa41007326',
        startDateVancancy: '7/24/2022',
        entryDateEmployee: '8/22/2022',
        workerType: 'Trainee',
        jobTitle: 'Senior Associate 2',
        office: 'Concepción',
        requestedBy: 'ecroxton45@istockphoto.com',
        los: 'IFS',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 13,
        action: 'in',
    },
    {
        requestID: '7c04aa22-31bb-438e-b07e-c4d7f049811d',
        startDateVancancy: '6/11/2022',
        entryDateEmployee: '10/6/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Partner',
        office: 'Puerto Montt',
        requestedBy: 'lstandfield46@vk.com',
        los: 'Assurance',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 9,
        action: 'pellentesque',
    },
    {
        requestID: '7f63e1b7-f94b-48ce-b3b9-ad1390d5fd5a',
        startDateVancancy: '3/24/2022',
        entryDateEmployee: '11/30/2022',
        workerType: 'Regular',
        jobTitle: 'Senior Associate 2',
        office: 'Concepción',
        requestedBy: 'qvanderbrug47@msn.com',
        los: 'Advisory',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 7,
        action: 'pede',
    },
    {
        requestID: '12a9075d-13e5-4674-9f96-9b9b46cc7cc5',
        startDateVancancy: '4/30/2022',
        entryDateEmployee: '6/16/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Senior Associate 2',
        office: 'Santiago',
        requestedBy: 'eboyes48@ehow.com',
        los: 'Assurance',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 9,
        action: 'in',
    },
    {
        requestID: '1e175bf9-77a9-4c02-a79a-08249b6ea21d',
        startDateVancancy: '9/18/2022',
        entryDateEmployee: '6/30/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Manager',
        office: 'Puerto Montt',
        requestedBy: 'ceden49@t.co',
        los: 'Tax',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 3,
        action: 'in',
    },
    {
        requestID: '6861813c-b0db-4738-9963-c51354b09e54',
        startDateVancancy: '4/4/2022',
        entryDateEmployee: '1/22/2022',
        workerType: 'Trainee',
        jobTitle: 'Senior Manager',
        office: 'Santiago',
        requestedBy: 'fgitthouse4a@hugedomains.com',
        los: 'Tax',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 6,
        action: 'purus',
    },
    {
        requestID: '9fb3da75-7a8d-48fc-836a-c8841dd6c5b0',
        startDateVancancy: '3/14/2022',
        entryDateEmployee: '6/22/2022',
        workerType: 'Regular',
        jobTitle: 'Senior Associate 2',
        office: 'Concepción',
        requestedBy: 'jmaccracken4b@blogs.com',
        los: 'Tax',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 15,
        action: 'integer',
    },
    {
        requestID: 'f3c51f8b-8719-4bd1-aba8-a394a7934180',
        startDateVancancy: '10/8/2022',
        entryDateEmployee: '10/18/2022',
        workerType: 'Trainee',
        jobTitle: 'Manager',
        office: 'Santiago',
        requestedBy: 'lrawcliff4c@nba.com',
        los: 'Tax',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 12,
        action: 'duis',
    },
    {
        requestID: 'faf1629d-611f-4ca4-bcbb-0429bd481658',
        startDateVancancy: '1/31/2022',
        entryDateEmployee: '8/1/2022',
        workerType: 'Trainee',
        jobTitle: 'Associate',
        office: 'Puerto Montt',
        requestedBy: 'gtomala4d@yellowpages.com',
        los: 'Assurance',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 6,
        action: 'ipsum',
    },
    {
        requestID: '18871183-7d12-4f82-9231-085b24fe1c9b',
        startDateVancancy: '7/2/2022',
        entryDateEmployee: '8/16/2022',
        workerType: 'Regular',
        jobTitle: 'Manager',
        office: 'Santiago',
        requestedBy: 'rkettlewell4e@mac.com',
        los: 'Assurance',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 2,
        action: 'justo',
    },
    {
        requestID: 'f99feaa1-e051-4d84-8e33-99dca3a9da0a',
        startDateVancancy: '7/2/2022',
        entryDateEmployee: '9/14/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Senior Manager',
        office: 'Concepción',
        requestedBy: 'bmacillrick4f@uiuc.edu',
        los: 'Advisory',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 10,
        action: 'nibh',
    },
    {
        requestID: '92f5a67b-0726-4f62-ab06-f89e0bd321b3',
        startDateVancancy: '8/29/2022',
        entryDateEmployee: '11/6/2022',
        workerType: 'Trainee',
        jobTitle: 'Associate',
        office: 'Concepción',
        requestedBy: 'kprazor4g@washington.edu',
        los: 'Advisory',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 5,
        action: 'mattis',
    },
    {
        requestID: 'f1cb3e9e-1575-4fd9-89d0-dc64e540ffca',
        startDateVancancy: '6/15/2022',
        entryDateEmployee: '10/18/2022',
        workerType: 'Trainee',
        jobTitle: 'Manager',
        office: 'Concepción',
        requestedBy: 'jginnaly4h@washington.edu',
        los: 'IFS',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 14,
        action: 'turpis',
    },
    {
        requestID: 'b6894e4d-d6d5-4d8f-9bff-dd3b661e222d',
        startDateVancancy: '10/28/2022',
        entryDateEmployee: '7/12/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Associate',
        office: 'Santiago',
        requestedBy: 'twaterhouse4i@netscape.com',
        los: 'Advisory',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Creada',
        totalVacancies: 4,
        action: 'id',
    },
    {
        requestID: '55d9de1a-de53-483c-a17d-2a53724a281c',
        startDateVancancy: '6/3/2022',
        entryDateEmployee: '11/7/2022',
        workerType: 'Trainee',
        jobTitle: 'Manager',
        office: 'Concepción',
        requestedBy: 'jallerton4j@uol.com.br',
        los: 'Assurance',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 9,
        action: 'lobortis',
    },
    {
        requestID: '7531be3f-ccb6-49ff-ac08-fe9a3a8a8a13',
        startDateVancancy: '2/10/2022',
        entryDateEmployee: '3/27/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Associate',
        office: 'Concepción',
        requestedBy: 'glyvon4k@nationalgeographic.com',
        los: 'IFS',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Creada',
        totalVacancies: 11,
        action: 'lacinia',
    },
    {
        requestID: 'dc14f9db-ea91-4421-872f-c82257c63525',
        startDateVancancy: '1/14/2022',
        entryDateEmployee: '7/1/2022',
        workerType: 'Regular',
        jobTitle: 'Associate',
        office: 'Santiago',
        requestedBy: 'dmacgiolla4l@vinaora.com',
        los: 'IFS',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 5,
        action: 'orci',
    },
    {
        requestID: '28681c53-b6d6-4ff9-90cf-aea5f6b5286f',
        startDateVancancy: '11/30/2022',
        entryDateEmployee: '8/21/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Senior Associate 2',
        office: 'Puerto Montt',
        requestedBy: 'aoliva4m@ifeng.com',
        los: 'Tax',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 13,
        action: 'ac',
    },
    {
        requestID: 'fb7ff748-3eba-45b5-9bfd-47c16c32796c',
        startDateVancancy: '3/9/2022',
        entryDateEmployee: '12/20/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Senior Manager',
        office: 'Santiago',
        requestedBy: 'shaken4n@usa.gov',
        los: 'Tax',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 9,
        action: 'dictumst',
    },
    {
        requestID: '40814dda-9df5-400a-8dc5-fc68fd3b4744',
        startDateVancancy: '6/4/2022',
        entryDateEmployee: '10/2/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Manager',
        office: 'Puerto Montt',
        requestedBy: 'afurnell4o@linkedin.com',
        los: 'IFS',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Creada',
        totalVacancies: 15,
        action: 'velit',
    },
    {
        requestID: '88f7f4ef-60e5-4ba1-bd86-880ded4ab696',
        startDateVancancy: '8/29/2022',
        entryDateEmployee: '9/22/2022',
        workerType: 'Regular',
        jobTitle: 'Associate',
        office: 'Puerto Montt',
        requestedBy: 'kaldie4p@reverbnation.com',
        los: 'Assurance',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 2,
        action: 'imperdiet',
    },
    {
        requestID: '6c505b0f-be86-4dda-a72a-e005dd9496c6',
        startDateVancancy: '1/8/2022',
        entryDateEmployee: '6/1/2022',
        workerType: 'Trainee',
        jobTitle: 'Associate 2',
        office: 'Puerto Montt',
        requestedBy: 'dgarlette4q@theatlantic.com',
        los: 'Assurance',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 3,
        action: 'et',
    },
    {
        requestID: 'f667db92-df90-4ac9-bbb7-0d034ea8026b',
        startDateVancancy: '4/18/2022',
        entryDateEmployee: '12/23/2022',
        workerType: 'Socio',
        jobTitle: 'Senior Manager',
        office: 'Concepción',
        requestedBy: 'shunston4r@guardian.co.uk',
        los: 'Assurance',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Creada',
        totalVacancies: 7,
        action: 'vel',
    },
    {
        requestID: 'b202f16e-e79a-44e6-8819-989d33c28b0e',
        startDateVancancy: '5/12/2022',
        entryDateEmployee: '7/12/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Associate 2',
        office: 'Santiago',
        requestedBy: 'oduker4s@spiegel.de',
        los: 'Tax',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 14,
        action: 'tempus',
    },
    {
        requestID: 'ca394c14-d6f6-4265-9fec-e5a7a51e76a4',
        startDateVancancy: '11/1/2022',
        entryDateEmployee: '12/18/2022',
        workerType: 'Trainee',
        jobTitle: 'Associate',
        office: 'Santiago',
        requestedBy: 'mharriman4t@altervista.org',
        los: 'Tax',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 12,
        action: 'dolor',
    },
    {
        requestID: 'efc9e62a-9a9c-475a-bd9d-0d5e57cadd40',
        startDateVancancy: '8/13/2022',
        entryDateEmployee: '3/3/2022',
        workerType: 'Socio',
        jobTitle: 'Senior Manager',
        office: 'Puerto Montt',
        requestedBy: 'bsellman4u@addthis.com',
        los: 'IFS',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 14,
        action: 'in',
    },
    {
        requestID: '6dc5a06c-c968-4c84-b69b-e975ca814f38',
        startDateVancancy: '7/25/2022',
        entryDateEmployee: '10/18/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Senior Manager',
        office: 'Concepción',
        requestedBy: 'skennerknecht4v@uiuc.edu',
        los: 'Tax',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 10,
        action: 'sed',
    },
    {
        requestID: '7a0cedf7-e6c3-43ad-abf0-4c97162ea65a',
        startDateVancancy: '12/7/2022',
        entryDateEmployee: '5/24/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Senior Associate 2',
        office: 'Santiago',
        requestedBy: 'efretter4w@wikipedia.org',
        los: 'Tax',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 8,
        action: 'vitae',
    },
    {
        requestID: '89091904-b0f2-438d-8250-05ec50ce0c4d',
        startDateVancancy: '7/9/2022',
        entryDateEmployee: '6/26/2022',
        workerType: 'Regular',
        jobTitle: 'Senior Associate 2',
        office: 'Santiago',
        requestedBy: 'tlozano4x@squidoo.com',
        los: 'Tax',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 7,
        action: 'velit',
    },
    {
        requestID: '8d72ad98-527d-4b01-87d4-2e11b91d9128',
        startDateVancancy: '1/19/2022',
        entryDateEmployee: '5/29/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Partner',
        office: 'Santiago',
        requestedBy: 'mgodman4y@over-blog.com',
        los: 'Tax',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 4,
        action: 'posuere',
    },
    {
        requestID: '68b280ec-e490-48ea-9285-7e6ab6f78075',
        startDateVancancy: '3/22/2022',
        entryDateEmployee: '3/21/2022',
        workerType: 'Socio',
        jobTitle: 'Senior Associate 2',
        office: 'Concepción',
        requestedBy: 'emourant4z@washington.edu',
        los: 'IFS',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 13,
        action: 'id',
    },
    {
        requestID: '7804cbdc-22c2-48d5-a055-cb26dcb22965',
        startDateVancancy: '11/29/2022',
        entryDateEmployee: '1/5/2022',
        workerType: 'Trainee',
        jobTitle: 'Associate 2',
        office: 'Santiago',
        requestedBy: 'pstarmore50@ifeng.com',
        los: 'IFS',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Creada',
        totalVacancies: 13,
        action: 'ut',
    },
    {
        requestID: 'b43c16fa-cd28-49d1-81c1-7393a72f70dc',
        startDateVancancy: '7/14/2022',
        entryDateEmployee: '8/13/2022',
        workerType: 'Socio',
        jobTitle: 'Partner',
        office: 'Santiago',
        requestedBy: 'ejonah51@miitbeian.gov.cn',
        los: 'Advisory',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 1,
        action: 'pede',
    },
    {
        requestID: 'fa5de89b-115e-4f3b-aa2c-956c8ce95a8a',
        startDateVancancy: '11/4/2022',
        entryDateEmployee: '12/29/2022',
        workerType: 'Regular',
        jobTitle: 'Associate',
        office: 'Puerto Montt',
        requestedBy: 'hskyram52@goodreads.com',
        los: 'Assurance',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Creada',
        totalVacancies: 7,
        action: 'eu',
    },
    {
        requestID: 'e6496fac-636f-4aef-a9cb-965fc0bcfe6a',
        startDateVancancy: '5/1/2022',
        entryDateEmployee: '4/11/2022',
        workerType: 'Regular',
        jobTitle: 'Senior Manager',
        office: 'Puerto Montt',
        requestedBy: 'ivonhagt53@spiegel.de',
        los: 'Assurance',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 13,
        action: 'sollicitudin',
    },
    {
        requestID: '8bc4c45a-51f7-449f-9c74-9fceca4cf73d',
        startDateVancancy: '1/21/2022',
        entryDateEmployee: '1/27/2022',
        workerType: 'Socio',
        jobTitle: 'Senior Manager',
        office: 'Concepción',
        requestedBy: 'aox54@sina.com.cn',
        los: 'Tax',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 12,
        action: 'condimentum',
    },
    {
        requestID: '00ade81a-8fb2-4cfe-b863-ed4353e54777',
        startDateVancancy: '10/3/2022',
        entryDateEmployee: '2/3/2022',
        workerType: 'Trainee',
        jobTitle: 'Senior Associate 2',
        office: 'Puerto Montt',
        requestedBy: 'mkenrat55@desdev.cn',
        los: 'Assurance',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 1,
        action: 'sapien',
    },
    {
        requestID: 'a3873b97-71a2-4212-824e-31a05e70c7ee',
        startDateVancancy: '3/24/2022',
        entryDateEmployee: '8/28/2022',
        workerType: 'Trainee',
        jobTitle: 'Manager',
        office: 'Puerto Montt',
        requestedBy: 'bsousa56@sakura.ne.jp',
        los: 'Tax',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 7,
        action: 'vitae',
    },
    {
        requestID: 'b501357b-381d-4a30-906e-87159981c521',
        startDateVancancy: '3/13/2022',
        entryDateEmployee: '2/17/2022',
        workerType: 'Trainee',
        jobTitle: 'Senior Associate 2',
        office: 'Puerto Montt',
        requestedBy: 'wbarron57@dropbox.com',
        los: 'Advisory',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 7,
        action: 'eget',
    },
    {
        requestID: '7e75489e-72fd-4423-9a3e-81c31c00659b',
        startDateVancancy: '1/7/2022',
        entryDateEmployee: '10/11/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Associate',
        office: 'Puerto Montt',
        requestedBy: 'mdownton58@epa.gov',
        los: 'IFS',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 3,
        action: 'vestibulum',
    },
    {
        requestID: 'f0193464-531d-4a1e-9d0e-00d6fac38f39',
        startDateVancancy: '12/5/2022',
        entryDateEmployee: '8/11/2022',
        workerType: 'Regular',
        jobTitle: 'Associate 2',
        office: 'Concepción',
        requestedBy: 'thollidge59@mit.edu',
        los: 'Assurance',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 14,
        action: 'eleifend',
    },
    {
        requestID: '14929605-b853-43db-bf0e-ba035552ec38',
        startDateVancancy: '12/19/2022',
        entryDateEmployee: '1/23/2022',
        workerType: 'Socio',
        jobTitle: 'Associate 2',
        office: 'Puerto Montt',
        requestedBy: 'nhayne5a@deliciousdays.com',
        los: 'IFS',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 1,
        action: 'quam',
    },
    {
        requestID: '964af038-7e88-45c7-90e8-dc0391fa4fc0',
        startDateVancancy: '8/13/2022',
        entryDateEmployee: '4/10/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Associate',
        office: 'Santiago',
        requestedBy: 'jcampos5b@people.com.cn',
        los: 'IFS',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 9,
        action: 'ipsum',
    },
    {
        requestID: '4bffca06-8872-4d93-be3b-ed4954889ad4',
        startDateVancancy: '9/25/2022',
        entryDateEmployee: '5/24/2022',
        workerType: 'Regular',
        jobTitle: 'Senior Manager',
        office: 'Santiago',
        requestedBy: 'iclamo5c@scientificamerican.com',
        los: 'Advisory',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Creada',
        totalVacancies: 5,
        action: 'non',
    },
    {
        requestID: 'c1120f24-bb11-4977-a1a3-68425f211728',
        startDateVancancy: '4/28/2022',
        entryDateEmployee: '11/20/2022',
        workerType: 'Trainee',
        jobTitle: 'Senior Manager',
        office: 'Santiago',
        requestedBy: 'dpasby5d@go.com',
        los: 'Tax',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Creada',
        totalVacancies: 4,
        action: 'id',
    },
    {
        requestID: '35166698-d135-496a-9e6c-adfb48216fee',
        startDateVancancy: '3/15/2022',
        entryDateEmployee: '3/14/2022',
        workerType: 'Socio',
        jobTitle: 'Associate',
        office: 'Concepción',
        requestedBy: 'wnoyce5e@noaa.gov',
        los: 'IFS',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Creada',
        totalVacancies: 7,
        action: 'placerat',
    },
    {
        requestID: '96000e28-2990-44e6-8049-5562fe885102',
        startDateVancancy: '11/2/2022',
        entryDateEmployee: '11/8/2022',
        workerType: 'Trainee',
        jobTitle: 'Associate',
        office: 'Concepción',
        requestedBy: 'idubber5f@ucsd.edu',
        los: 'Tax',
        requestStatus: 'Pendiente',
        vacancyIsCreated: 'Pendiente',
        totalVacancies: 1,
        action: 'aliquam',
    },
    {
        requestID: 'ca99a9d3-64ee-4ff1-b532-0e0685cd9761',
        startDateVancancy: '1/11/2022',
        entryDateEmployee: '9/5/2022',
        workerType: 'Plazo Fijo',
        jobTitle: 'Senior Manager',
        office: 'Concepción',
        requestedBy: 'pburker5g@joomla.org',
        los: 'Assurance',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 9,
        action: 'sem',
    },
    {
        requestID: 'd947e543-f661-4ed0-9592-8824be889458',
        startDateVancancy: '8/10/2022',
        entryDateEmployee: '1/24/2022',
        workerType: 'Socio',
        jobTitle: 'Associate',
        office: 'Santiago',
        requestedBy: 'vreimer5h@mozilla.com',
        los: 'Tax',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 2,
        action: 'vestibulum',
    },
    {
        requestID: '58b21a3d-977b-4ebb-b295-3a63527bc196',
        startDateVancancy: '3/3/2022',
        entryDateEmployee: '12/26/2022',
        workerType: 'Trainee',
        jobTitle: 'Senior Associate 2',
        office: 'Santiago',
        requestedBy: 'cendricci5i@feedburner.com',
        los: 'IFS',
        requestStatus: 'Rechazado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 15,
        action: 'erat',
    },
    {
        requestID: 'fd582591-4452-42e5-a705-bd89bd9dc3bb',
        startDateVancancy: '10/16/2022',
        entryDateEmployee: '10/26/2022',
        workerType: 'Socio',
        jobTitle: 'Senior Manager',
        office: 'Santiago',
        requestedBy: 'grozsa5j@ask.com',
        los: 'IFS',
        requestStatus: 'Aprobado',
        vacancyIsCreated: 'Creada',
        totalVacancies: 7,
        action: 'erat',
    },
];
const onChange = (pagination, filters, sorter, extra) => {
    console.log('params', pagination, filters, sorter, extra);
};

const Home = () => {
    return (
        <>
            <Table
                columns={columns}
                dataSource={data}
                className="w-full"
                scroll={{
                    x: '100%',
                    y: '430px',
                }}
            />
        </>
    );
};
export default Home;
